---
id: tokyurb06
base_name: tokyurb06
tags: []
version: 1.0.0
presentation_date: 2013/06/29
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author:
  markup_language: :rd
  name: Haruka Yoshihara
  email: yshr04hrk@gmail.com
  rubygems_user: yoshihara
  slideshare_user: yoshihara
  speaker_deck_user: 
